DROP DATABASE IF EXISTS ERP_Order
CREATE DATABASE ERP_Order;
GO

USE ERP_Order;
GO

DROP TABLE IF EXISTS Address
CREATE TABLE Address
(
	 AddressID		INT			NOT NULL	IDENTITY(10000000, 1)
	,Zip			VARCHAR(10)	NOT NULL
	,Street			VARCHAR(50)	NOT NULL
	,Comment		VARCHAR(50)	NOT NULL
	,Neighborhood	VARCHAR(50)	NOT NULL
	,City			VARCHAR(50)	NOT NULL
	,State			VARCHAR(2)	NOT NULL
	,Country		VARCHAR(50)	NOT NULL
	,Deleted		BIT			NOT NULL
	,InsertDate		DATETIME	NOT NULL

	CONSTRAINT PK_AddressID PRIMARY KEY(AddressID)
);

DROP TABLE IF EXISTS Client
CREATE TABLE Client
(
	 ClientID		INT			NOT NULL	IDENTITY(10000000, 1)
	,AddressID		INT			NOT NULL
	,Deleted		BIT			NOT NULL
	,InsertDate		DATETIME	NOT NULL

	CONSTRAINT PK_ClientID PRIMARY KEY(ClientID)

	CONSTRAINT PK_Client_AddressID FOREIGN KEY(AddressID)
	REFERENCES Address(AddressID)
);

DROP TABLE IF EXISTS Supplier
CREATE TABLE Supplier
(
	 SupplierID		INT			NOT NULL	IDENTITY(10000000, 1)
	,AddressID		INT			NOT NULL
	,Deleted		BIT			NOT NULL
	,InsertDate		DATETIME	NOT NULL

	CONSTRAINT PK_SupplierID PRIMARY KEY(SupplierID)

	CONSTRAINT PK_Supplier_AddressID FOREIGN KEY(AddressID)
	REFERENCES Address(AddressID)
);

DROP TABLE IF EXISTS Orders
CREATE TABLE Orders
(
	 OrderID		INT			NOT NULL	IDENTITY(10000000, 1)
	,ClientID		INT			NOT NULL
	,Deleted		BIT			NOT NULL
	,InsertDate		DATETIME	NOT NULL

	CONSTRAINT PK_OrderID PRIMARY KEY(OrderID)

	CONSTRAINT FK_Orders_ClientID FOREIGN KEY(ClienteID)
	REFERENCES Client(ClientID)
);

DROP TABLE IF EXISTS Items
CREATE TABLE Items
(
	 ItemID			INT			NOT NULL	IDENTITY(10000000, 1)
	,SupplierID		INT			NOT NULL
	,Deleted		BIT			NOT NULL
	,InsertDate		DATETIME	NOT NULL

	CONSTRAINT PK_ItemID PRIMARY KEY(ItemID)

	CONSTRAINT FK_Items_SupplierID FOREIGN KEY(SupplierID)
	REFERENCES Supplier(SupplierID)
);

DROP TABLE IF EXISTS Order_Item
CREATE TABLE Order_Items
(
	 Order_ItemID	INT			NOT NULL	IDENTITY(10000000, 1)
	,OrderID		INT			NOT NULL
	,ItemID			INT			NOT NULL
	,Deleted		BIT			NOT NULL
	,InsertDate		DATETIME	NOT NULL

	CONSTRAINT PK_Order_ItemID PRIMARY KEY(Order_ItemID)

	CONSTRAINT FK_Order_Items_OrderID FOREIGN KEY(OrderID)
	REFERENCES Orders(OrderID),

	CONSTRAINT FK_Order_Items_ItemID FOREIGN KEY(ItemID)
	REFERENCES Items(ItemID)
);

DROP TABLE IF EXISTS Inventory_Item
CREATE TABLE Inventory
(
	 Inventory_ItemID	INT			NOT NULL	IDENTITY(10000000, 1)
	,Quantity			INT			NOT NULL
	,ItemID				INT			NOT NULL
	,SupplierID			INT			NOT NULL
	,Deleted			BIT			NOT NULL
	,InsertDate			DATETIME	NOT NULL
	
	CONSTRAINT Inventory_Item PRIMARY KEY(Inventory_ItemID)

	CONSTRAINT FK_Inventory_Item_ItemID FOREIGN KEY(ItemID)
	REFERENCES Items(ItemID)

	CONSTRAINT FK_Inventory_Item_SupplierID FOREIGN KEY(SupplierID)
	REFERENCES Supplier(SupplierID)
);